set_property PACKAGE_PIN V18 [get_ports {VGA_red}]
set_property IOSTANDARD "LVCMOS33" [get_ports {VGA_red}]
set_property PACKAGE_PIN AA21 [get_ports {VGA_green}]
set_property IOSTANDARD "LVCMOS33" [get_ports {VGA_green}]
set_property PACKAGE_PIN AB19 [get_ports {VGA_blue}]
set_property IOSTANDARD "LVCMOS33" [get_ports {VGA_blue}]
set_property PACKAGE_PIN AA19 [get_ports {hsync}]
set_property IOSTANDARD "LVCMOS33" [get_ports {hsync}]
set_property PACKAGE_PIN Y19 [get_ports {vsync}]
set_property IOSTANDARD "LVCMOS33" [get_ports {vsync}]

set_property PACKAGE_PIN Y9 [get_ports {clk100}]
set_property IOSTANDARD "LVCMOS33" [get_ports {clk100}]

set_property PACKAGE_PIN N15 [get_ports {ouest}]
set_property IOSTANDARD "LVCMOS33" [get_ports {ouest}]
set_property PACKAGE_PIN P16 [get_ports {S1}]
set_property IOSTANDARD "LVCMOS33" [get_ports {S1}]
set_property PACKAGE_PIN R18 [get_ports {est}]
set_property IOSTANDARD "LVCMOS33" [get_ports {est}]
set_property PACKAGE_PIN T18 [get_ports {nord}]
set_property IOSTANDARD "LVCMOS33" [get_ports {nord}]
set_property PACKAGE_PIN R16 [get_ports {sud}]
set_property IOSTANDARD "LVCMOS33" [get_ports {sud}]

set_property PACKAGE_PIN T22 [get_ports {led[0]}]
set_property PACKAGE_PIN T21 [get_ports {led[1]}]
set_property PACKAGE_PIN U22 [get_ports {led[2]}]
set_property PACKAGE_PIN U21 [get_ports {led[3]}]
set_property PACKAGE_PIN V22 [get_ports {led[4]}]
set_property PACKAGE_PIN W22 [get_ports {led[5]}]
set_property PACKAGE_PIN U19 [get_ports {led[6]}]
set_property PACKAGE_PIN U14 [get_ports {led[7]}]
set_property IOSTANDARD "LVCMOS33" [get_ports {led[*]}]

set_property PACKAGE_PIN F22 [get_ports {S0}]
set_property IOSTANDARD "LVCMOS33" [get_ports {S0}]

set_property PACKAGE_PIN H22 [get_ports {S2}]
set_property IOSTANDARD "LVCMOS33" [get_ports {S2}]
set_property PACKAGE_PIN F21 [get_ports {S3}]
set_property IOSTANDARD "LVCMOS33" [get_ports {S3}]

set_property PACKAGE_PIN AB7 [get_ports {rot_a}]
set_property IOSTANDARD "LVCMOS33" [get_ports {rot_a}]
set_property PACKAGE_PIN AB6 [get_ports {rot_b}]
set_property IOSTANDARD "LVCMOS33" [get_ports {rot_b}]
set_property PACKAGE_PIN AA4 [get_ports {rot_button}]
set_property IOSTANDARD "LVCMOS33" [get_ports {rot_button}]

set_property PACKAGE_PIN M15 [get_ports {txd}]
set_property IOSTANDARD "LVCMOS33" [get_ports {txd}]
set_property PACKAGE_PIN H17 [get_ports {rxd}]
set_property IOSTANDARD "LVCMOS33" [get_ports {rxd}]
